import Head from 'next/head'
import Header from '../components/Header'
import HomeMain from '../components/HomeMain'
import { useSession, signIn, signOut } from "next-auth/react"


const BASE_URL = 'https://api.spotify.com'

export default function Home() {
  const { data: session } = useSession()
  if(!session) return (
    <main className='h-screen flex flex-col items-center pt-32 text-center'>
      <h2 className='text-3xl font-semibold text-gray-400 mb-5'>
        Spotify Stats
      </h2>
      <p className='mb-8 text-green-600'>
      Please login with your spotify account, to see your track or artist ranking!
      </p>
      <button className='w-[300px] bg-green-600 py-1.5 hover:scale-105 ease-in-out transition duration-200' onClick={() => signIn()}>Sign in</button>
    </main>
  )
  return (
    <div>
      <Head>
        <title>Spotify Stats | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className='bg-green-400 h-[1px] w-full mb-24' />

      <HomeMain />

    </div>
  )
}

// export async function getServerSideProps(ctx) {
//   // const data = await fetch(`${BASE_URL}/${process.env.S}`).then(res => res.json())
// }